version: '3.8'

services:
  db:
    container_name: mongodb
    image: mongo:4.4.14
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      sbi:
        ipv4_address: 192.168.0.3

  nrf:
    container_name: nrf
    image: nrf:v3.1.1
    command: --config nrfcfg.yaml
    volumes:
      - ./configs/integrated/configsat/nrfcfg.yaml:/free5gc/nrfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      sbi:
        ipv4_address: 192.168.0.4
    depends_on:
      - db

  amf:
    container_name: amf
    image: amf:v3.1.1b
    entrypoint: bash ./entrypoint.sh
    volumes:
      - ./configs/integrated/configsat/amfcfg.yaml:/free5gc/amfcfg.yaml
      - ./configs/integrated/configsat/amf.sh:/free5gc/entrypoint.sh
    cap_add:
      - NET_ADMIN
    environment:
      GIN_MODE: release
    networks:
      sbi:
        ipv4_address: 192.168.0.5
      n123-terrestrial:
        ipv4_address: 192.168.15.5
    depends_on:
      - nrf

  uereg:
    container_name: uereg
    image: uereg:latest
    command: --config populatecfg.yaml
    volumes:
      - ./configs/integrated/configsat/uereg.yaml:/populate/populatecfg.yaml
    environment:
      GIN_MODE: release
    networks:
      sbi:
        ipv4_address: 192.168.0.13
    depends_on:
      - db
      - amf
      - nrf
  
  upfMec:
    container_name: upfMec
    image: upf:v3.1.1
    command: bash ./upf-iptables.sh
    volumes:
      - ./configs/integrated/configsat/upfcfgmec.yaml:/free5gc/upfcfg.yaml
      - ./configs/integrated/configsat/upf-iptablesmec.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      satterminal-network:
        ipv4_address: 192.168.30.4 
      pfcp:
        ipv4_address: 192.168.5.5
      # pfcp:
      #   ipv4_address: 192.168.5.4 #eth1
      # n123-terrestrial:
      #   ipv4_address: 192.168.15.4 #eth0
      # data-networkN6:
      #   ipv4_address: 192.168.10.3
  
  # upfTer:
  #   container_name: upfTer
  #   image: upf:v3.1.1
  #   command: bash ./upf-iptables.sh
  #   #command: bash -c "./upf-iptables.sh && ./free5gc-upfd -c ./upfcfg.yaml"
  #   volumes:
  #     - ./configs/integrated/configsat/upfcfgter.yaml:/free5gc/upfcfg.yaml
  #     - ./configs/integrated/configsat/upf-iptablester.sh:/free5gc/upf-iptables.sh
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     pfcp:
  #       ipv4_address: 192.168.5.4 #eth1
  #     n123-terrestrial:
  #       ipv4_address: 192.168.15.4 #eth0

  smf:
    container_name: smf
    image: smf:v3.1.1b
    #command: --config smfcfg.yaml --uerouting uerouting.yaml
    entrypoint: bash ./entrypoint.sh
    volumes:
      - ./configs/integrated/configsat/smfcfg.yaml:/free5gc/smfcfg.yaml
      - ./configs/integrated/configsat/uerouting.yaml:/free5gc/uerouting.yaml
      - ./configs/integrated/configsat/smf.sh:/free5gc/entrypoint.sh
    cap_add:
      - NET_ADMIN
    networks:
      sbi:
        ipv4_address: 192.168.0.9
      pfcp:
        ipv4_address: 192.168.5.3
    depends_on:
      - nrf
      #- upfTer
      - upfMec

  ausf:
    container_name: ausf
    image: ausf:v3.1.1
    command: --config ausfcfg.yaml
    volumes:
      - ./configs/integrated/configsat/ausfcfg.yaml:/free5gc/ausfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      sbi:
        ipv4_address: 192.168.0.6
    depends_on:
      - nrf

  nssf:
    container_name: nssf
    image: nssf:v3.1.1
    command: --config nssfcfg.yaml
    volumes:
      - ./configs/integrated/configsat/nssfcfg.yaml:/free5gc/nssfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      sbi:
        ipv4_address: 192.168.0.7
    depends_on:
      - nrf

  pcf:
    container_name: pcf
    image: pcf:v3.1.1
    command: --config pcfcfg.yaml
    volumes:
      - ./configs/integrated/configsat/pcfcfg.yaml:/free5gc/pcfcfg.yaml
    cap_add:
      - NET_ADMIN
    environment:
      GIN_MODE: release
    networks:
      sbi:
        ipv4_address: 192.168.0.8
    depends_on:
      - nrf

  udm:
    container_name: udm
    image: udm:v3.1.1
    command: --config udmcfg.yaml
    volumes:
      - ./configs/integrated/configsat/udmcfg.yaml:/free5gc/udmcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      sbi:
        ipv4_address: 192.168.0.10
    depends_on:
      - nrf

  udr:
    container_name: udr
    image: udr:v3.1.1
    command: --config udrcfg.yaml
    volumes:
      - ./configs/integrated/configsat/udrcfg.yaml:/free5gc/udrcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      sbi:
        ipv4_address: 192.168.0.11
    depends_on:
      - nrf

  gnbSat:
    container_name: gnbSat
    image: gnb:masterb
    entrypoint: bash ./entrypoint.sh
    volumes:
      - ./configs/integrated/configsat/gnbcfgsat.yaml:/gnb/gnbcfg.yaml
      - ./configs/integrated/configsat/gnb.sh:/gnb/entrypoint.sh
    cap_add:
      - NET_ADMIN
    networks:
      n123-terrestrial:
        ipv4_address: 192.168.15.7
      satgateway-network:
        ipv4_address: 192.168.35.3 #172.22.0.4
      # satgnb-network:
      #   ipv4_address: 192.168.40.3
    depends_on:
      - nrf
      - amf
      - upfMec
      - smf
      - pcf
      - ausf
      - gateway
      - satellite
      - terminal
  
  # gnbTer:
  #   container_name: gnbTer
  #   image: gnb:master
  #   command: --config gnbcfg.yaml
  #   #entrypoint: bash ./entrypoint.sh
  #   volumes:
  #     - ./configs/integrated/configsat/gnbcfgter.yaml:/gnb/gnbcfg.yaml
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     n123-terrestrial:
  #       ipv4_address: 192.168.15.3
  #   depends_on:
  #     - nrf
  #     - amf
  #     - upfTer
  #     - smf
  #     - pcf
  #     - ausf
  
  gateway:
    container_name: ${GW_CONTAINER_NAME:-gateway}
    build: /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/gateway/
    entrypoint: ./opensand_config/entrypoint.sh
    ports:
      - "3141"
      - "5358"
      - "5926"
    volumes:
      - /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/gateway/config:/opensand_config
      - /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/src/:/root/go/src
    networks:
      satgateway-network:
        ipv4_address: 192.168.35.4 #172.22.0.3
      # pfcp:
      #   ipv4_address: 192.168.5.5
      emulation: #sat:
        ipv4_address: ${EMU_NETWORK_HEAD:-172.20}.0.3 #172.20.0.3 192.168.40.4
        priority: 900
      gwlan:
        ipv4_address: "${GW_NETWORK_HEAD:-172.22}.0.3"
        priority: 1000
        ipv6_address: ${GW_IP6_HEAD:-2001:660}:6602:142:0:0:1:1
    privileged: true
    cap_add:
      - ALL
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      GOPATH: /root/go
      GIN_MODE: release

  satellite:
    container_name: ${SAT_CONTAINER_NAME:-satellite}
    build: /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/satellite/
    entrypoint: ./opensand_config/entrypoint.sh
    ports:
      - "3141"
      - "5358"
      - "5926"
      - "${SAT_PORT_NUMBER:-5656}:5656"
    volumes:
      - /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/satellite/config:/opensand_config
      - /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/satellite/attenuation_scenario:/attenuation_scenario
      - /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/satellite/delay_scenario:/delay_scenario
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      emulation:
        ipv4_address: ${EMU_NETWORK_HEAD:-172.20}.0.2 #192.168.40.3
      # satgnb-network:
      #   ipv4_address: 192.168.40.4
    privileged: true
    environment:
      DISPLAY: :1
      GIN_MODE: release
    depends_on:
      - "gateway"
      - "terminal"

  terminal:
    container_name: ${ST_CONTAINER_NAME:-terminal}
    build: /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/terminal/
    entrypoint: ./opensand_config/entrypoint.sh
    ports:
      - "3141"
      - "5358"
      - "5926"
    volumes:
      - /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/terminal/config:/opensand_config
      - /home/vagrant/3D-NTN/build_images/opensand-simulator/opensand/src/:/root/go/src
    environment:
      GOPATH: /root/go
      GIN_MODE: release
    networks:
      satterminal-network:
        ipv4_address: 192.168.30.3 #172.21.0.4
      emulation:
        ipv4_address: ${EMU_NETWORK_HEAD:-172.20}.0.4 #192.168.40.5
        priority: 900
      stlan:
        ipv4_address: "${ST_NETWORK_HEAD:-172.21}.0.4"
        priority: 1000
        ipv6_address: ${ST_IP6_HEAD:-2001:661}:6602:142:0:0:1:2
    privileged: true
    cap_add:
      - ALL
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  # ueter:
  #   container_name: ueter
  #   image: ue:masterb
  #   entrypoint: bash ./entrypoint.sh
  #   volumes:
  #     - ./configs/integrated/configsat/uecfgter.yaml:/ue/uecfg.yaml
  #     - ./configs/integrated/configsat/ueter.sh:/ue/entrypoint.sh
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun
  #   networks:
  #     n123-terrestrial:
  #       ipv4_address: 192.168.15.6
  #     # satterminal-network:
  #     #   ipv4_address: 192.168.30.5 #172.21.0.5
  #   depends_on:
  #     - gnbTer
  
  uesat:
    container_name: uesat
    image: ue:masterb
    entrypoint: bash ./entrypoint.sh
    volumes:
      - ./configs/integrated/configsat/uecfgsat.yaml:/ue/uecfg.yaml
      - ./configs/integrated/configsat/uesat.sh:/ue/entrypoint.sh
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      satterminal-network:
        ipv4_address: 192.168.30.5 #172.21.0.5
      n123-terrestrial:
        ipv4_address: 192.168.15.8
    depends_on:
      - terminal

networks:
  pfcp:
    name: pfcp
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
    driver_opts:
      com.docker.network.bridge.name: pfcp-network
  sbi:
    name: sbi
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
    driver_opts:
      com.docker.network.bridge.name: sbi-network
  n123-terrestrial:
    name: n123-terrestrial
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.15.0/24
    driver_opts:
      com.docker.network.bridge.name: ter-network
  satterminal-network:
    name: satterminal-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.30.0/24 #172.21.0.0/24
    driver_opts:
      com.docker.network.bridge.name: sat-ter-net
  satgateway-network:
    name: satgateway-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.35.0/24 #172.22.0.0/24
    driver_opts:
      com.docker.network.bridge.name: sat-gate-net
  # satgnb-network:
  #   name: satgnb-network
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 192.168.40.0/24 #172.22.0.0/24
  #   driver_opts:
  #     com.docker.network.bridge.name: sat-gnb-net
  emulation:
    name: ${EMU_NETWORK_NAME:-emulation}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${EMU_NETWORK_HEAD:-172.20}.0.0/24" #192.168.40.0/24
    driver_opts:
      com.docker.network.bridge.name: emu-net
  gwlan:
    name: ${GW_NETWORK_NAME:-gwlan}
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "${GW_NETWORK_HEAD:-172.22}.0.0/24"
        - subnet: "${GW_IP6_HEAD:-2001:660}:6602:142::1/64"
  stlan:
    name: ${ST_NETWORK_NAME:-stlan}
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "${ST_NETWORK_HEAD:-172.21}.0.0/24"
        - subnet: "${ST_IP6_HEAD:-2001:661}:6602:142::1/64"
  gui:
    name: ${GUI_NETWORK_NAME:-gui}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${GUI_NETWORK_HEAD:-172.25}.0.0/24"
          gateway: "${GUI_NETWORK_HEAD:-172.25}.0.1"

volumes:
  dbdata: